-- Project Atlas first owner bootstrap script.
--
-- Purpose:
--   Attach an existing Supabase Auth user to the first Atlas tenant.
--
-- Safety model:
--   - psql variables only; do not edit this file with personal identifiers.
--   - Transactional and idempotent.
--   - Fails before commit when the Auth user, tenant, owner role, or membership
--     state is ambiguous.
--   - No destructive statement.
--
-- Required psql variables:
--   atlas_bootstrap_user_id     Existing auth.users.id UUID.
--   atlas_bootstrap_user_email  Existing auth.users.email.
--
-- Optional psql variable:
--   atlas_bootstrap_tenant_name Tenant to create or reuse.
--                               Defaults to Atlas Test Tenant.

\set ON_ERROR_STOP on

\if :{?atlas_bootstrap_user_id}
\else
\error 'Missing required psql variable atlas_bootstrap_user_id.'
\endif

\if :{?atlas_bootstrap_user_email}
\else
\error 'Missing required psql variable atlas_bootstrap_user_email.'
\endif

\if :{?atlas_bootstrap_tenant_name}
\else
\set atlas_bootstrap_tenant_name 'Atlas Test Tenant'
\endif

begin;

create temporary table atlas_first_owner_bootstrap_params (
  user_id uuid not null,
  user_email text not null,
  tenant_name text not null
);

insert into atlas_first_owner_bootstrap_params (user_id, user_email, tenant_name)
values (
  :'atlas_bootstrap_user_id'::uuid,
  btrim(:'atlas_bootstrap_user_email'),
  btrim(:'atlas_bootstrap_tenant_name')
);

create temporary table atlas_first_owner_bootstrap_result (
  tenant_id uuid not null,
  tenant_name text not null,
  tenant_status text not null,
  user_id uuid not null,
  profile_email text,
  tenant_user_status text not null,
  role_slug text not null
);

do $$
declare
  bootstrap_user_id uuid;
  bootstrap_user_email text;
  bootstrap_tenant_name text;
  bootstrap_tenant_id uuid;
  owner_role_id uuid;
  auth_user_match_count integer;
  auth_email_count integer;
  tenant_match_count integer;
  owner_role_count integer;
  other_active_memberships integer;
  other_active_owners integer;
  final_membership_count integer;
begin
  select p.user_id, p.user_email, p.tenant_name
  into bootstrap_user_id, bootstrap_user_email, bootstrap_tenant_name
  from atlas_first_owner_bootstrap_params p;

  if bootstrap_user_email is null or bootstrap_user_email = '' then
    raise exception 'atlas_bootstrap_user_email must not be empty.';
  end if;

  if bootstrap_tenant_name is null or bootstrap_tenant_name = '' then
    raise exception 'atlas_bootstrap_tenant_name must not be empty.';
  end if;

  select count(*)
  into auth_user_match_count
  from auth.users u
  where u.id = bootstrap_user_id
    and lower(u.email) = lower(bootstrap_user_email);

  if auth_user_match_count <> 1 then
    raise exception 'Expected exactly one auth.users row matching the supplied id and email; observed %.', auth_user_match_count;
  end if;

  select count(*)
  into auth_email_count
  from auth.users u
  where lower(u.email) = lower(bootstrap_user_email);

  if auth_email_count <> 1 then
    raise exception 'Expected exactly one auth.users row matching the supplied email; observed %.', auth_email_count;
  end if;

  select count(*)
  into tenant_match_count
  from public.tenants t
  where t.name = bootstrap_tenant_name;

  if tenant_match_count > 1 then
    raise exception 'Expected at most one tenant with the supplied name; observed %.', tenant_match_count;
  end if;

  if tenant_match_count = 0 then
    insert into public.tenants (name, status)
    values (bootstrap_tenant_name, 'active')
    returning id into bootstrap_tenant_id;
  else
    select t.id
    into bootstrap_tenant_id
    from public.tenants t
    where t.name = bootstrap_tenant_name;

    update public.tenants
    set status = 'active',
        updated_at = now()
    where id = bootstrap_tenant_id
      and status <> 'active';
  end if;

  select count(*)
  into owner_role_count
  from public.roles r
  where r.slug = 'owner';

  if owner_role_count <> 1 then
    raise exception 'Expected exactly one owner role; observed %.', owner_role_count;
  end if;

  select r.id
  into owner_role_id
  from public.roles r
  where r.slug = 'owner';

  select count(*)
  into other_active_memberships
  from public.tenant_users tu
  where tu.user_id = bootstrap_user_id
    and tu.tenant_id <> bootstrap_tenant_id
    and tu.status = 'active';

  if other_active_memberships > 0 then
    raise exception 'User already has active tenant membership outside the target tenant; observed %.', other_active_memberships;
  end if;

  select count(*)
  into other_active_owners
  from public.tenant_users tu
  join public.roles r on r.id = tu.role_id
  where tu.tenant_id = bootstrap_tenant_id
    and tu.user_id <> bootstrap_user_id
    and tu.status = 'active'
    and r.slug = 'owner';

  if other_active_owners > 0 then
    raise exception 'Target tenant already has a different active owner; observed %.', other_active_owners;
  end if;

  insert into public.profiles (id, email, full_name)
  select
    u.id,
    u.email,
    coalesce(
      nullif(btrim(u.raw_user_meta_data ->> 'full_name'), ''),
      nullif(btrim(u.raw_user_meta_data ->> 'name'), ''),
      u.email
    )
  from auth.users u
  where u.id = bootstrap_user_id
  on conflict (id) do update set
    email = excluded.email,
    full_name = excluded.full_name,
    updated_at = now();

  insert into public.tenant_users (tenant_id, user_id, role_id, status)
  values (bootstrap_tenant_id, bootstrap_user_id, owner_role_id, 'active')
  on conflict (tenant_id, user_id) do update set
    role_id = excluded.role_id,
    status = 'active',
    updated_at = now();

  select count(*)
  into final_membership_count
  from public.tenant_users tu
  join public.roles r on r.id = tu.role_id
  where tu.tenant_id = bootstrap_tenant_id
    and tu.user_id = bootstrap_user_id
    and tu.status = 'active'
    and r.slug = 'owner';

  if final_membership_count <> 1 then
    raise exception 'Bootstrap verification failed; expected one active owner membership, observed %.', final_membership_count;
  end if;

  insert into atlas_first_owner_bootstrap_result (
    tenant_id,
    tenant_name,
    tenant_status,
    user_id,
    profile_email,
    tenant_user_status,
    role_slug
  )
  select
    t.id,
    t.name,
    t.status,
    p.id,
    p.email,
    tu.status,
    r.slug
  from public.tenants t
  join public.tenant_users tu on tu.tenant_id = t.id
  join public.roles r on r.id = tu.role_id
  join public.profiles p on p.id = tu.user_id
  where t.id = bootstrap_tenant_id
    and tu.user_id = bootstrap_user_id
    and tu.status = 'active'
    and r.slug = 'owner';
end;
$$;

select
  tenant_id,
  tenant_name,
  tenant_status,
  user_id,
  profile_email,
  tenant_user_status,
  role_slug
from atlas_first_owner_bootstrap_result;

commit;
